<a href="https://colab.research.google.com/github/dpalma1996/Derian_Palma_Q-Data-Analytics-2026-2027/blob/main/Examen_Derian_Palma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://media.licdn.com/dms/image/v2/D4D3DAQGHFRw0kcxJUg/image-scale_191_1128/image-scale_191_1128/0/1666168591190/it_academy_barcelonactiva_cover?e=2147483647&v=beta&t=s8V1Kbvj6KeyArt5yBWDgIulRMH9ctGG4QMiBvvKGpM"/>

# <span style="color: rgb(230, 0, 126);"> PROVA PYTHON</span>

Curs Fonaments de Programació i Dades

Nom alumne: 	Derian Palma Quirós

Data: 10/07/26

### <span style="color: rgb(230, 0, 126);"> Com funciona la prova?</span>
A continuació et plantegem una sèrie de problemes en python. Has d'escriure la solució a tots ells.

### <span style="color: rgb(230, 0, 126);"> Com s’avaluarà la prova?</span>
Cada pregunta té una puntuació, especificada al final de cadascuna, però per superar la prova hauràs de obtenir un 6,5 com a mínim.

Recorda que l’obtenció del títol no depèn només de la superació d’aquesta prova sinó del seguiment i les tasques entregades prèviament.

**IMPORTANT: pots utilitzar exercicis que ja tinguis fets, però no pots utilitzar chatbots de IA (com chatGPT)**

### <span style="color: rgb(230, 0, 126);"> Com s’ha d’entregar?</span>
L’examen haurà de ser entregat per Discord al docent per missatge privat, durant el temps que estàs al cibernàrium fent la prova.

#### <span style="color: rgb(230, 0, 126);"> Exercici 1 (2p)</span>

Crea una funció que rebi una llista de números com a paràmetre.
La funció ha de recórrer la llista i retornar una altra llista amb aquestes dades:
- Quantitat de números que hi ha a la llista
- Valor máxim de la llista

Després mostra per pantalla aquests dos valors.

DADES PER LA LLISTA:

40, 20, 33, 5, 14, 45, 87, 3, 10, 99

*Fes l'exercici sense utilitzar funcions de python com max(), min(), len(), count()*

In [ ]:
#escriu el teu codi python

# declaro desde el inicio la variable/lista
llista = [40, 20, 33, 5, 14, 45, 87, 3, 10, 99]


def func(list):
  # prefiero crear las variables que me servirán dentro de la función
  # las variables del contador y del máximo
  c = 0
  m = 0


  # aquí de momento uso len() para usarla con el rango,
  # NO la uso para sustituir el contador, solo para el bucle
  for i in range(len(list)):

    # este es mi contador
    c = c+1

    # esta lógica de comparación me servirá para encontrar el máximo
    # partimos de un máximo que es cero y comparamos cada vez
    # y si es mayor lo guardamos
    # no hace falta el caso contrario
    if list[i] > m:
      m = list[i]

  # devuelve ambos valores, el contador y el máximo
  return c, m

# llamamos a la función
# y almacenamos los valores devueltos por la función
# en dos variables de una vez
cant, max = func(llista)

# mostramos un mensaje con lo que nos solicitan
print(f"Quantitat de números que hi ha a la llista: {cant}. \nValor máxim de la llista: {max}.")

Quantitat de números que hi ha a la llista: 10.
Valor máxim de la llista: 99.

#### <span style="color: rgb(230, 0, 126);"> Exercici 2 (2p)</span>

Crea una funció que demani 5 noms de ciutats i el seu respectiu país. A mesura que vas demanant les dades has d'afegir a un diccionari de nacionals les ciutats espanyoles i a un diccionari d'estrangers la resta.

La funció ha de retornar només el diccionari de nacionals.

Després, mostra per pantalla el diccionari de nacionals.


DADES PER DEMANAR:

Barcelona - Espanya || Paris - França || Munich - Alemanya || Sevilla - Espanya || Madrid - Espanya

In [ ]:
#escriu el teu codi python

def func():
  nacionals = {}
  estrangers = {}
  for i in range(5):
    c = input(f"Dame el nombre de la ciudad {i+1}: ")
    p = input(f"Dame el nombre del país {i+1}: ")
    # en la comparación solamente estoy evaluando "Espanya"
    # las posibilidades en minúscula, con 'ñ', etc las haré si me da tiempo
    # pero considero que el ejercicio no lo demanda porque indica cuáles serán
    # los datos a ingresar:
    # Barcelona - Espanya || Paris - França || Munich - Alemanya || Sevilla - Espanya || Madrid - Espanya
    if p == "Espanya":
      # esta es mi solución para agregar al diccionario:
      # no le veo sentido agregarlas a un diccionario sabiendo que
      # todas serán nacionales o extranjeras,
      # siento que lo lógico del diccionario
      # sería tener de claves "país" y "ciudad" y
      # de valores los datos correspondientes,
      # pero si el diccionario ya es de nacional y/o extranjero
      # poner de clave "país" sería redundante
      # así pues, el diccionario será como una lista con
      # claves: simplemente una numeración del elemento
      # valores: el dato de la ciudad
      nacionals[f"ciudad {i+1}"] = c
    else:
      estrangers[f"ciudad {i+1}"] = c

  # devolver nada más el diccionario de nacionals
  return nacionals

# llamo a la función desde el print
print(f"\nEl diccionari de nacionals:\n{func()}")

Dame el nombre de la ciudad 1: Barcelona
Dame el nombre del país 1: Espanya
Dame el nombre de la ciudad 2: Paris
Dame el nombre del país 2: França
Dame el nombre de la ciudad 3: Munich
Dame el nombre del país 3: Alemanya
Dame el nombre de la ciudad 4: Sevilla
Dame el nombre del país 4: Espanya
Dame el nombre de la ciudad 5: Madrid
Dame el nombre del país 5: Espanya

El diccionari de nacionals:
{'ciudad 1': 'Barcelona', 'ciudad 4': 'Sevilla', 'ciudad 5': 'Madrid'}

NOTA: reconozco que pude afinarlo para que el número de la ciudad en el diccionario final estuviera ordenado {'ciudad 1': 'Barcelona', 'ciudad 1': 'Sevilla', 'ciudad 3': 'Madrid'} en lugar de {'ciudad 1': 'Barcelona', 'ciudad 4': 'Sevilla', 'ciudad 5': 'Madrid'}.

con un poco más de tiempo lo afino por estética pero no es una restricción del diccionario que piden creo

#### <span style="color: rgb(230, 0, 126);"> Exercici 3 (2,5p)</span>

Treballaràs amb un dataset de llibres més venuts a Amazon durant diversos anys. El dataset inclou informació sobre el títol del llibre, l'autor, la puntuació mitjana dels usuaris, el nombre de ressenyes, el preu, l’any de publicació i el gènere.

Carrega el csv "bestsellers with categories.csv" i realitza les següents tasques:

a. Genera dos nous datasets, un per a cada grup: (0,75p)
- Grup 1: Selecciona els de l'autor "Stephen King" amb una puntuació d’usuari superior o igual a 4.5 i un nombre de ressenyes superior a 3.000.
- Grup 2: Selecciona els llibres amb preu superior a 5 €, publicats abans de 2015 i escrits per autors que tinguin un nom que comenci per "H".

 Quants registres té cada grup?

In [ ]:
#escriu el teu codi python

import pandas as pd

data1 = pd.read_csv(
    "/content/sample_data/bestsellers with categories-1.csv"
)

# explorar el df
data1.head()

# creación del grupo
gr1 = data1[
    (data1["Author"] == "Stephen King") &
    (data1["User Rating"] >= 4.5) &
    (data1["Reviews"] > 3000)
]

# lo muestro (no se ve por estar dentro de esta misma celda y ejecutar el print)
gr1

# respondo la pregunta (esto sí se ve)
print(f"El Grup 1 té {gr1.shape[0]} Registres")

gr2 = data1[
    (data1["Price"] > 5) &
    (data1["Year"] < 2015) &
    (data1["Author"].str.startswith("H"))
]

# lo muestro (no se ve por estar dentro de esta misma celda y ejecutar el print)
gr2

# respondo la pregunta (esto sí se ve)
print(f"El Grup 2 té {gr2.shape[0]} Registres")

El Grup 1 té 2 Registres
El Grup 2 té 1 Registres

(ignorar la siguiente celda, es solo para visualizar los nombres de las columnas y poder trabajar (explorar los datos))

---

In [ ]:
data1.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

b. Realitza els següents càlculs: (0,75p)

Agrupa les dades del dataset inicial per autor i calcula la mitjana de preu dels seus llibres

Agrupa les dades del dataset inicial any de publicació i gènere, i calcula el màxim de puntuació d'usuaris

In [ ]:
#escriu el teu codi python

En las siguientes dos celdas muestro esta resolución, preferí separarlas para que se vean ambos resultados

In [ ]:
# Agrupa les dades del dataset inicial per autor i calcula la mitjana de preu dels seus llibres

data1.groupby("Author")["Price"].mean()

Author
Abraham Verghese              11.000000
Adam Gasiewski                 6.000000
Adam Mansbach                  9.000000
Adir Levy                     13.000000
Admiral William H. McRaven    11.000000
                                ...
Walter Isaacson               20.333333
William Davis                  6.000000
William P. Young               8.000000
Wizards RPG Team              27.000000
Zhi Gang Sha                  11.500000
Name: Price, Length: 248, dtype: float64

In [ ]:
# Agrupa les dades del dataset inicial any de publicació i gènere, i calcula el màxim de puntuació d'usuaris

data1.groupby(["Year","Genre"])["User Rating"].max()

Year  Genre
2009  Fiction        4.8
      Non Fiction    4.8
2010  Fiction        4.8
      Non Fiction    4.8
2011  Fiction        4.8
      Non Fiction    4.9
2012  Fiction        4.9
      Non Fiction    4.9
2013  Fiction        4.9
      Non Fiction    4.9
2014  Fiction        4.9
      Non Fiction    4.9
2015  Fiction        4.9
      Non Fiction    4.9
2016  Fiction        4.9
      Non Fiction    4.9
2017  Fiction        4.9
      Non Fiction    4.9
2018  Fiction        4.9
      Non Fiction    4.8
2019  Fiction        4.9
      Non Fiction    4.9
Name: User Rating, dtype: float64

c. Afegeix una nova columna anomenada "RangPreu": (0,75p)

- Valor "Car" si el preu és major a 25.
- Valor "Mig" si el preu està entre 10 i 25 (els dos preus inclosos).
- Valor "Barat" si el preu és menor a 10

In [ ]:
#escriu el teu codi python

# se crea la nueva columna
data1["RangPreu"] = ""

# precio mayor que 25
data1.loc[
    data1["Price"] > 25,
    "RangPreu"
] = "Car"

# precio entre 10 y 25
data1.loc[
    (data1["Price"] >= 10) &
    (data1["Price"] <= 25),
    "RangPreu"
] = "Mig"

# precio menor que 10
data1.loc[
    data1["Price"] < 10,
    "RangPreu"
] = "Barat"

# mostrar el resultado
print(data1[["Name", "Price", "RangPreu"]].head())

                                                Name  Price RangPreu
0                      10-Day Green Smoothie Cleanse      8    Barat
1                                  11/22/63: A Novel     22      Mig
2            12 Rules for Life: An Antidote to Chaos     15      Mig
3                             1984 (Signet Classics)      6    Barat
4  5,000 Awesome Facts (About Everything!) (Natio...     12      Mig

d. Elimina totes les columnes excepte "Name", "Author" i "Year" i guarda el resultat en un nou DataFrame anomenat llibres_filtrats. (0,75p)

In [ ]:
#escriu el teu codi python

# se crea un nuevo df solo con las columnas indicadas
# para mí es más directo que eliminar las otras
# aunque 'técnicamente' no estoy eliminando nada pero funciona
# y se ve más lógico y entendible

llibres_filtrats = data1[
    [
        "Name",
        "Author",
        "Year"
    ]
]

# mostrar el df filtrado
# para mí se ve mejor sin print
llibres_filtrats.head()

,Name,Author,Year
0,10-Day Green Smoothie Cleanse,JJ Smith,2016
1,11/22/63: A Novel,Stephen King,2011
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,2018
3,1984 (Signet Classics),George Orwell,2017
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,2019

#### <span style="color: rgb(230, 0, 126);"> Exercici 4 (3,5p)</span>


En una empresa de logística, cada repartidor té assignades entregues amb una quantitat estimada de productes. Sovint, per diversos motius (errors, manca d'estoc, incidències...), la quantitat real entregada pot ser inferior a la prevista. Això afecta la qualitat del servei.

Objectiu:

Escriu una funció que, donat el dataset lliuraments.csv, faci el següent:

- Agrupar per repartidor i calcular els lliuraments de cadascú
- Agrupar per repartidor i calcular els lliuraments incomplets
- Calcular el % d'entregues incompletes (incompletes / totals * 100)
- Calcular la mitjana d'entregues incompletes de tots els repartidors
- Retornar el dataframe només amb els repartidors que estan per sobre de la mitjana

Crida la funció amb el dataframe lliuraments.csv i mostra els repartidors que estan per sobre de la mitjana.

----------------------------------------------------------------------------------------------------------------------

Ajuda: per "ajuntar" les series o dataframes que generis a les dues primeres agrupacions pots utilizar el mètode concat

nou_data_frame = pd.concat([serie1, serie2], axis=1)  
aquesta instrucció genera un dataframe "ajuntant" la serie1 i la serie2 (o si fosin els df1 o df2 també funcionaria).

Després, pots renombrar les columnes així:
nou_data_frame.columns = ['nom_columna1', 'nom_columna2']

In [ ]:
#escriu el teu codi python

import pandas as pd

data2 = pd.read_csv(
    "/content/sample_data/lliuraments-1.csv"
)

data2.head()


def func(df):

  df_nou = df.copy()


  # Agrupar per repartidor i calcular els lliuraments de cadascú
  totals = df_nou.groupby("repartidor").size()

  print("lliuraments de cadascú\n",totals)


  # Agrupar per repartidor i calcular els lliuraments incomplets
  df_incomplets = df_nou[
        df_nou["quantitat_entregada"] < df_nou["quantitat_prevista"]
    ]

  entregues_incomplets = df_incomplets.groupby("repartidor").size()

  print("\nlliuraments incomplets\n",entregues_incomplets)


  # Calcular el % d'entregues incompletes (incompletes / totals * 100)

  # primero habría que concatenar:

  resultat = pd.concat(
        [totals, entregues_incomplets],
        axis=1
    )

  # se nombran las columnas
  resultat.columns = [
      "totals",
      "entregues_incomplets"
  ]

  # los repartidores sin entregas incompletas aparecen con NaN.
  # se sustituyen esos valores por 0.
  resultat["entregues_incomplets"] = (
      resultat["entregues_incomplets"].fillna(0)
  )

  # por fin se hace el cálculo
  resultat["percentatge_incomplets"] = (
    resultat["entregues_incomplets"]
        / resultat["totals"]
        * 100
      )
  print("\n% d'entregues incompletes:\n",resultat["percentatge_incomplets"])


  # Calcular la mitjana d'entregues incompletes de tots els repartidors

  # se calcula la media del porcentaje de entregas incompletas
  mitjana = resultat["percentatge_incomplets"].mean()

  # se filtra los repartidores que están por encima de la media
  resultat_final = resultat[
      resultat["percentatge_incomplets"] > mitjana
  ]


  # Retornar el dataframe només amb els repartidors que estan per sobre de la mitjana
  return resultat_final

# se llama a la función
dada = func(data2)
print(dada)

lliuraments de cadascú
 repartidor
Alberto    3
Ana        3
Carlos     3
Laura      3
Luis       3
dtype: int64

lliuraments incomplets
 repartidor
Alberto    3
Ana        3
Carlos     1
Laura      3
Luis       1
dtype: int64

% d'entregues incompletes:
 repartidor
Alberto    100.000000
Ana        100.000000
Carlos      33.333333
Laura      100.000000
Luis        33.333333
Name: percentatge_incomplets, dtype: float64
            totals  entregues_incomplets  percentatge_incomplets
repartidor
Alberto          3                     3                   100.0
Ana              3                     3                   100.0
Laura            3                     3                   100.0

NOTA: algo me pasó con los porcentajes de entregas incompletas porque creo que no corresponden, me faltó revisar el cálculo o al concatenar algo falló

(ignorar la siguiente celda, es solo para visualizar los nombres de las columnas y poder trabajar (explorar los datos))

---

In [ ]:
data2.head()

,Lliurament,repartidor,quantitat_prevista,quantitat_entregada,Entrega_completa
0,LL1,Carlos,10,10,SI
1,LL2,Ana,8,5,NO
2,LL3,Alberto,12,11,NO
3,LL4,Luis,6,6,SI
4,LL5,Laura,15,12,NO